### ISSUE TITLE
Deconflict trivia, block & tetris

### ISSUE THREAD

**Issue by its-a-lisa** [SupplyChainSandbox/trivia#6]
##  Issue Description:
trivia, block, & quadquizaminios (aka "Tetris") are 'awareness & adoption' games that teach our supply chain concepts by getting the participants to answer questions. 

At first glance they may appear 'tests to reward the most knowledgeable supply chain nerds' but they are actually A&A/training. 

Since we have 3 games about the same body of knowledge, we probably should pool resources and make conscious decisions on overlap (concepts worth repeating and seeing in every game) vs uniqueness.

##  Latest Status (2/17/2021):
Project Managers discussed this issue and decided that it is an optimization issue and rather than spend time coordinating on this prior to the MVP it is better to let folks remain creative within their products and work to deconflict later when necessary.

**Comment by sparrell** [comment]
I don't have permission to edit the issue, but I believe the issue is that trivia, block, & quadquizaminios (aka "Tetris") are 'awareness & adoption' games that teach our supply chain concepts by getting the participants to answer questions. At first glance they may appear 'tests to reward the most knowledgeable supply chain nerds' but they are actually A&A/training. Since we have 3 games about the same body of knowledge, we probably should pool resources and make conscious decisions on overlap (concepts worth repeating and seeing in every game) vs uniqueness.

**Comment by alisabryant** [comment]
@sparrell you should be able to edit the issue now. 

I created a [new document](https://docs.google.com/document/d/1XX9aetKx4cYcsUhKO0ivqJPSJQw5oIrhFXi-Np5MN9I/edit#heading=h.8zq75jv7f2e5) to start the process of deconflicting
